import sqlalchemy as db 
from sqlalchemy import Column, Integer, String, JSON
from metadata.database.database import engine
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import session , sessionmaker


Base = declarative_base()



class newMetaData(Base):
    __tablename__ = "new_metadata"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String)
    timezone = Column(String)
    is_duration = Column(String)
    is_time = Column(String)
    is_date = Column(String)
    is_datetime = Column(String)
    duration_unit = Column(String)
    date_format = Column(String)
    is_phone = Column(String)
    is_email = Column(String)
    is_link = Column(String)
    is_multi_picklist = Column(String)
    is_country = Column(String)
    is_state = Column(String)
    is_city = Column(String)
    is_pincode = Column(String)
    is_address_line = Column(String)
    is_noun = Column(String)
    currency_code = Column(String)
    entity = Column(String)
    text_encoding = Column(String)
    is_case_sensitive = Column(String)
    text_case = Column(String)
    is_html = Column(String)
    is_text = Column(String)
    max_value = Column(String)
    min_value = Column(String)
    standard_deviation = Column(String)
    mean_value = Column(String)
    mode_value = Column(String)
    median_value = Column(String)
    lt_zero_count = Column(String)
    gt_zero_count = Column(String)
    eq_zero_count = Column(String)
    lt_mean_count = Column(String)
    gt_mean_count = Column(String)
    eq_mean_count = Column(String)
    lt_median_count = Column(String)
    gt_median_count = Column(String)
    eq_median_count = Column(String)
    is_float = Column(String)
    is_integer = Column(String)
    float_precision = Column(String)
    data_trend = Column(String)
    data_distribution = Column(String)
    data_trend_direction = Column(String)
    field_id = Column(String)
    object_id = Column(UUID(as_uuid=True))
    object_name = Column(String)
    system_id = Column(String)
    project_id = Column(String)
    tenant_key = Column(String)
    label = Column(String)
    description = Column(String)
    datatype = Column(String)
    max_length = Column(String)
    min_length = Column(String)
    data_count = Column(String)
    null_count = Column(String)
    data_density = Column(String)
    ext_system = Column(String)
    ext_object = Column(String)
    ext_field = Column(String)
    fk_object = Column(String)
    fk_field = Column(String)
    is_pk = Column(String)
    is_required = Column(String)
    is_fk = Column(String)
    is_unique = Column(String)
    is_null = Column(String)
    is_encoded = Column(String)
    is_fixed_length = Column(String)
    for_migrate = Column(String)
    field_source = Column(String)
    outliers = Column(String)
    is_picklist = Column(String)
    picklist_values = Column(JSON)
    unique_values_count = Column(String)
    data_format = Column(String)
    owner = Column(String)
    permission = Column(String)
    mask = Column(String)
    security_class = Column(String)
    caseSensitive = Column(String)
    htmlFormatted = Column(String)
    type = Column(String)
    precision = Column(String)
    referenceTo = Column(String)
    length = Column(String)
    relationshipName = Column(String)
    idLookup = Column(String)
    unique = Column(String)
    picklistValues = Column(String) 
    permissionable = Column(String)
    externalId = Column(String)
    autoNumber = Column(String)
    byteLength = Column(String)
    calculated = Column(String)
    calculatedFormula = Column(String)
    defaultValue = Column(String)
    formulaTreatNullNumberAsZero = Column(String)
    nillable = Column(String)
    data_quality = Column(String)
    modified_by = Column(String)


Base.metadata.create_all(engine)